Run proper specs (#14)
* Update GitHub Actions workflow to install 'fish' on linux and macos. Remove 'test.sh' script from workflow and replace it with the 'integration-tests' script.

* Update version in Cargo.lock and remove test.sh from tools

* Update usage of OPENAI_API_KEY in integration-tests script

* Refactor the order of operations in the integration tests script. The 'Hello World 0' initialization and commit sequence is moved up for better workflow consistency.

* Remove debug flag from Cargo installation in integration tests

* Update git-ai hooks and config execution in integration-tests script

This commit modifies the scripts/integration-tests script. The changes provide better debugging information by outputting messages when certain git-ai commands, such as 'hook' and 'config set', fail as expected. This will help in understanding test failures and successful runs better.

* Update GitHub workflow to add restore-keys for job matrix

* Update actions/checkout and actions/cache versions in CD workflow

* Force reinstall of Cargo in integration tests

* Add config reset subcommand and update dependencies

* Fix indentation in main function

diff --git a/scripts/integration-tests b/scripts/integration-tests
--- a/scripts/integration-tests
+++ b/scripts/integration-tests
@@ -1,7 +1,7 @@
 #!/usr/bin/env fish
 
 set -x fish_trace 1
-set -x OPENAI_API_KEY $OPENAI_API_KEY
+set -Ux OPENAI_API_KEY $OPENAI_API_KEY
 set -x RUST_LOG debug
 
 if not test -n "$OPENAI_API_KEY"
@@ -31,7 +31,7 @@ end
 
 set DIR /tmp/git-ai-test
 
-cargo install --debug --path . || fail "Cargo installation failed"
+cargo install --force --path . || fail "Cargo installation failed"
 
 rm -rf $DIR
 mkdir $DIR
@@ -43,23 +43,24 @@ git config user.email "hello@world.com"
 git config --global init.defaultBranch main
 git branch -m main
 
-git-ai hook
+git-ai hook || echo "As expected"
 git-ai hook install || fail "Hook installation failed"
 git-ai hook uninstall || fail "Hook uninstallation failed"
 git-ai hook install || fail "Hook reinstallation failed"
 git-ai hook reinstall || fail "Hook reinstall failed"
 
-echo "Hello World 0" >README.md
-git add README.md
-git commit --no-edit || fail "Initial commit failed"
-git status --porcelain || fail "Git status failed after initial commit"
-
-git-ai config
-git-ai config set
+git-ai config reset
+git-ai config || echo "As expected"
+git-ai config set || echo "As expected"
 git-ai config set model gpt-4 || fail "Setting model failed"
 git-ai config set max-tokens 512 || fail "Setting max tokens failed"
 git-ai config set max-commit-length 1024 || fail "Setting max commit length failed"
 git-ai config set openai-api-key "$OPENAI_API_KEY" || fail "Setting OpenAI API key failed"
+
+echo "Hello World 0" >README.md
+git add README.md
+git commit --no-edit || fail "Initial commit failed"
+git status --porcelain || fail "Git status failed after initial commit"
 
 # Test case: commit -m
 echo "Hello World" >README.md
